server:
  port: 8030

  security:
    jwt:
      key:
        private: ${SECURITY_JWT_KEY_PRIVATE}
        user-generator: ${SECURITY_JWT_KEY_USER_GENERATOR}

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost/users
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: debug